---
- hosts: vms
  environment:
    PYTHONPATH: "{{ lookup('env','PYTHONPATH') }}:/usr/local/lib/python2.7/dist-packages:/usr/local/lib/python2.7/site-packages"
  remote_user: root
  become: yes
  become_method: sudo
  tasks:
    #    - name: upgrade all packages
    #      package:
    #        name: "*"
    #        state: latest
  
    - name: install development packages
      package: name={{ item }}
        state=present
      with_items:
        - python3
        - atop
        - htop
        - curl
        - tmux
        - mcedit
        - nano
  
    - name: Set up multiple authorized keys
      authorized_key:
        user: root
        state: present
        key: '{{ item }}'
      with_file:
        - public_keys/alfredo.pub
        - public_keys/denner.pub
        - public_keys/fabiano.pub
        - public_keys/flavio.pub